In [1]:
import imageio
import torch

In [17]:
img_arr = imageio.imread('../jupyter home/dataset/chapter 4/R-C.jpg')

C:\Users\WIN10\AppData\Local\Temp\ipykernel_19516\1760084411.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('../jupyter home/dataset/chapter 4/R-C.jpg')


In [8]:
img_arr.shape

(1280, 720, 3)

In [12]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [15]:
batch

tensor([[[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]],


        [[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0

In [65]:
import os

data_dir = 'F:\jupyter home\dataset\chapter 4\demo_256'
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.jpg']

# global img_t

for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2,0,1)
    img_t = img_t[:3]
#     batch[i].shape, img_t.shape
    batch[i] = img_t

C:\Users\WIN10\AppData\Local\Temp\ipykernel_19516\385995829.py:9: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [66]:
batch = batch.float() 

In [67]:
batch

tensor([[[[246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          ...,
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.]],

         [[246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          ...,
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.]],

         [[246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          ...,
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ...

In [68]:
batch.shape

torch.Size([3, 3, 256, 256])

In [69]:
batch /= 255.0

In [62]:
batch

tensor([[[[0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          ...,
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647]],

         [[0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          ...,
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647]],

         [[0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0.9647, 0.9647, 0.9647],
          [0.9647, 0.9647, 0.9647,  ..., 0

In [70]:
n_channels = batch.shape[1]

In [71]:
n_channels

3

In [77]:
global mean, std

for c in range(n_channels):
    mean = torch.mean(batch[:,c])
    std = torch.std(batch[:,c]) # 标准差
    batch[:,c] = (batch[:,c]-mean)/std

In [76]:
std

tensor(0.4040)

In [74]:
mean

tensor(0.5700)

In [80]:
batch

tensor([[[[1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328],
          [1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328],
          [1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328],
          ...,
          [1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328],
          [1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328],
          [1.2328, 1.2328, 1.2328,  ..., 1.2328, 1.2328, 1.2328]],

         [[1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887],
          [1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887],
          [1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887],
          ...,
          [1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887],
          [1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887],
          [1.0887, 1.0887, 1.0887,  ..., 1.0887, 1.0887, 1.0887]],

         [[0.9769, 0.9769, 0.9769,  ..., 0.9769, 0.9769, 0.9769],
          [0.9769, 0.9769, 0.9769,  ..., 0.9769, 0.9769, 0.9769],
          [0.9769, 0.9769, 0.9769,  ..., 0

### 4.2 表格数据

In [3]:
import csv
import numpy as np

In [5]:
wine_path = "F:\jupyter home\dataset\chapter 4\winequality-white .csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=';', skiprows=1)

wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [7]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

In [8]:
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [9]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [10]:
data = wineq[:, :-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [12]:
target = wineq[:, -1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [13]:
target = wineq[:, -1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

4.3.4 独热编码

In [14]:
target_onehot = torch.zeros(target.shape[0],10)

In [16]:
target_onehot,target.shape[0]

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 4898)

In [19]:
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [20]:
target.unsqueeze(1)

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

In [18]:
target_unssqueezed = target.unsqueeze(1)

In [22]:
data_mean = torch.mean(data, dim = 0)
data_mean,data

(tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
         1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01]),
 tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]))

In [23]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [25]:
data_normalized = (data - data_mean)/torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

4.3.6 寻找阈值

In [27]:
bad_indexes = target <= 3
bad_indexes

tensor([False, False, False,  ..., False, False, False])

In [35]:
bad_index_torch = torch.le(target, 3)
bad_index_torch.sum()

tensor(20)

In [30]:
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [32]:
bad_data = data[bad_indexes]
bad_data

tensor([[8.5000e+00, 2.6000e-01, 2.1000e-01, 1.6200e+01, 7.4000e-02, 4.1000e+01,
         1.9700e+02, 9.9800e-01, 3.0200e+00, 5.0000e-01, 9.8000e+00],
        [5.8000e+00, 2.4000e-01, 4.4000e-01, 3.5000e+00, 2.9000e-02, 5.0000e+00,
         1.0900e+02, 9.9130e-01, 3.5300e+00, 4.3000e-01, 1.1700e+01],
        [9.1000e+00, 5.9000e-01, 3.8000e-01, 1.6000e+00, 6.6000e-02, 3.4000e+01,
         1.8200e+02, 9.9680e-01, 3.2300e+00, 3.8000e-01, 8.5000e+00],
        [7.1000e+00, 3.2000e-01, 3.2000e-01, 1.1000e+01, 3.8000e-02, 1.6000e+01,
         6.6000e+01, 9.9370e-01, 3.2400e+00, 4.0000e-01, 1.1500e+01],
        [6.9000e+00, 3.9000e-01, 4.0000e-01, 4.6000e+00, 2.2000e-02, 5.0000e+00,
         1.9000e+01, 9.9150e-01, 3.3100e+00, 3.7000e-01, 1.2600e+01],
        [1.0300e+01, 1.7000e-01, 4.7000e-01, 1.4000e+00, 3.7000e-02, 5.0000e+00,
         3.3000e+01, 9.9390e-01, 2.8900e+00, 2.8000e-01, 9.6000e+00],
        [7.9000e+00, 6.4000e-01, 4.6000e-01, 1.0600e+01, 2.4400e-01, 3.3000e+01,
         2.27

In [34]:
bad_data.shape

torch.Size([20, 11])

In [37]:
bad_data = data[target <= 3]
bad_data

tensor([[8.5000e+00, 2.6000e-01, 2.1000e-01, 1.6200e+01, 7.4000e-02, 4.1000e+01,
         1.9700e+02, 9.9800e-01, 3.0200e+00, 5.0000e-01, 9.8000e+00],
        [5.8000e+00, 2.4000e-01, 4.4000e-01, 3.5000e+00, 2.9000e-02, 5.0000e+00,
         1.0900e+02, 9.9130e-01, 3.5300e+00, 4.3000e-01, 1.1700e+01],
        [9.1000e+00, 5.9000e-01, 3.8000e-01, 1.6000e+00, 6.6000e-02, 3.4000e+01,
         1.8200e+02, 9.9680e-01, 3.2300e+00, 3.8000e-01, 8.5000e+00],
        [7.1000e+00, 3.2000e-01, 3.2000e-01, 1.1000e+01, 3.8000e-02, 1.6000e+01,
         6.6000e+01, 9.9370e-01, 3.2400e+00, 4.0000e-01, 1.1500e+01],
        [6.9000e+00, 3.9000e-01, 4.0000e-01, 4.6000e+00, 2.2000e-02, 5.0000e+00,
         1.9000e+01, 9.9150e-01, 3.3100e+00, 3.7000e-01, 1.2600e+01],
        [1.0300e+01, 1.7000e-01, 4.7000e-01, 1.4000e+00, 3.7000e-02, 5.0000e+00,
         3.3000e+01, 9.9390e-01, 2.8900e+00, 2.8000e-01, 9.6000e+00],
        [7.9000e+00, 6.4000e-01, 4.6000e-01, 1.0600e+01, 2.4400e-01, 3.3000e+01,
         2.27

In [42]:
mid_data = data[(target > 3) & (target < 7)]
mid_data

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
        [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        ...,
        [ 6.6000,  0.3200,  0.3600,  ...,  3.1500,  0.4600,  9.6000],
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])

In [43]:
good_data = data[target >= 7]
good_data

tensor([[ 6.6000,  0.1600,  0.4000,  ...,  3.5400,  0.5200, 12.4000],
        [ 6.6000,  0.1700,  0.3800,  ...,  3.2500,  0.5500, 11.4000],
        [ 6.2000,  0.6600,  0.4800,  ...,  3.3300,  0.3900, 12.8000],
        ...,
        [ 6.2000,  0.2100,  0.2800,  ...,  3.2100,  1.0800, 12.1500],
        [ 6.2000,  0.4100,  0.2200,  ...,  3.0400,  0.7900, 13.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000]])

In [45]:
bad_mean = torch.mean(bad_data, dim=0)
bad_mean

tensor([7.6000e+00, 3.3325e-01, 3.3600e-01, 6.3925e+00, 5.4300e-02, 5.3325e+01,
        1.7060e+02, 9.9488e-01, 3.1875e+00, 4.7450e-01, 1.0345e+01])

In [47]:
mid_mean = torch.mean(mid_data, dim=0)
mid_mean

tensor([6.8869e+00, 2.8153e-01, 3.3644e-01, 6.7051e+00, 4.7841e-02, 3.5424e+01,
        1.4183e+02, 9.9447e-01, 3.1808e+00, 4.8707e-01, 1.0265e+01])

In [48]:
good_mean = torch.mean(good_data, dim=0)
good_mean

tensor([6.7251e+00, 2.6535e-01, 3.2606e-01, 5.2615e+00, 3.8160e-02, 3.4550e+01,
        1.2525e+02, 9.9241e-01, 3.2151e+00, 5.0014e-01, 1.1416e+01])

In [50]:
mid_mean = torch.mean(mid_data, dim=0)
mid_mean.shape

torch.Size([11])

In [52]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [54]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)

total_sulfur_data, predicted_indexes

(tensor([170., 132.,  97.,  ..., 111., 110.,  98.]),
 tensor([False,  True,  True,  ...,  True,  True,  True]))

In [56]:
actual_indexs = target > 5
actual_indexs.shape, actual_indexs.dtype, actual_indexs.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [58]:
n_matches = torch.sum(actual_indexs & predicted_indexes).item()
n_matches

2018

In [59]:
n_predicted = torch.sum(predicted_indexes).item()
n_predicted

2727

In [61]:
n_actual = torch.sum(actual_indexs).item()
n_actual

3258

In [64]:
n_matches/ n_predicted,  n_matches/ n_actual

(0.74000733406674, 0.6193984039287906)