# 3.2 多维数组

## 3.2.1 从Python 列表到 PyTorch张量

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0

In [4]:
a

[1.0, 2.0, 3.0]

## 3.2.2 构造第1个张量

In [2]:
import torch

In [6]:
a = torch.ones(3)

In [7]:
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0

In [11]:
a

tensor([1., 1., 2.])

## 3.2.3 张量的本质

In [12]:
points = torch.zeros(6)

In [13]:
points[1] = 4.0

In [14]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [15]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [19]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points.shape

torch.Size([3, 2])

In [21]:
points = torch.zeros(3, 2)

In [22]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [24]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
points[0,1]

tensor(1.)

In [26]:
points[0]

tensor([4., 1.])

# 3.3 张量索引

### 列表

In [28]:
some_list  = list(range(6))

In [29]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [30]:
some_list[1:4]

[1, 2, 3]

In [31]:
some_list[:5]

[0, 1, 2, 3, 4]

In [32]:
some_list[2:]

[2, 3, 4, 5]

In [33]:
some_list[: -1]

[0, 1, 2, 3, 4]

#### some_list[: -1] 到最后一个元素之前

In [35]:
some_list[::2]

[0, 2, 4]

In [36]:
some_list[1:4:2]

[1, 3]

### 张量

In [37]:
points[:]

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [38]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [39]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [41]:
points[1:3, 1:]

tensor([[3.],
        [1.]])

In [42]:
points[0]

tensor([4., 1.])

# 3.4命名张量

In [4]:
img_t = torch.randn(3, 5, 5)  # shape[channels, rows, columns]

In [5]:
img_t

tensor([[[-0.2409, -0.6451,  1.6245, -1.3412,  1.1031],
         [ 2.1000,  1.2271,  0.2801, -1.0641,  2.1849],
         [-0.8231,  0.3416, -0.2842, -0.0677,  0.5132],
         [ 1.1471, -1.1092, -0.9413,  0.2882, -0.1006],
         [ 1.0846, -0.4941, -1.7459,  2.2431, -0.1643]],

        [[ 0.5801, -1.0262, -0.3251, -0.5447, -0.4998],
         [ 1.1931,  1.2072, -1.2808,  0.6636,  0.1499],
         [-0.3880, -1.7968, -0.0102,  0.3905, -0.0942],
         [-0.0206,  1.2071,  0.0653, -0.6481, -1.1461],
         [-1.4864,  0.8137,  1.6081,  1.5094, -1.8110]],

        [[ 0.0393,  0.0101, -0.3967,  0.3660, -0.3695],
         [-1.2572,  1.3814, -0.3587, -1.3277,  0.5974],
         [-0.1609,  0.2092,  0.8411, -0.6474,  0.2741],
         [ 0.5174,  0.6575, -0.2815, -0.1079, -0.6953],
         [ 0.0227, -1.6432,  0.5298, -0.1878,  0.6991]]])

In [6]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [7]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [8]:
batch_t = torch.randn(2, 3, 5, 5)  # shape[batch, channels, rows, columns]

In [9]:
batch_t

tensor([[[[ 1.8634, -0.9144, -0.3084,  1.1259, -0.4351],
          [ 0.7520, -0.0857,  0.8630, -0.8805,  0.6951],
          [ 0.9289,  1.0509,  0.8075, -1.1594,  0.3582],
          [-1.3511,  0.9965,  0.8507, -0.1648, -0.1428],
          [-0.6640, -0.8038,  0.4159,  0.6124,  1.8575]],

         [[-0.4557,  1.8943,  1.9027,  0.4091,  0.8439],
          [ 0.3400, -1.8220,  0.1520,  1.8638,  0.8768],
          [-0.1834,  0.6668, -0.7675, -0.5469, -0.6828],
          [-1.6124,  1.1468, -0.1409,  0.2365,  0.1258],
          [-0.2987,  0.6618,  0.4295, -0.4708, -0.4584]],

         [[ 0.2063, -0.3508,  1.6016, -2.6981, -1.7821],
          [-1.9811, -0.1697, -0.3630, -0.2358, -2.0367],
          [ 0.4609, -2.3596,  1.8923, -0.2723, -0.8395],
          [-0.8075,  2.0424, -0.4092,  1.9773,  0.8965],
          [-0.8450,  0.2645,  0.1729, -0.5918,  1.0561]]],


        [[[ 0.8067, -0.0221,  0.2820,  1.4546, -0.8656],
          [ 0.7634, -0.0405,  0.0774, -0.4030, -0.8395],
          [-0.7891, -0.

#### torch.mean 求平均数

In [10]:
img_gray_naive = img_t.mean(-3) 

In [11]:
img_t.mean(-2) 

tensor([[ 0.6535, -0.1359, -0.2134,  0.0117,  0.7073],
        [-0.0243,  0.0810,  0.0115,  0.2742, -0.6802],
        [-0.1677,  0.1230,  0.0668, -0.3810,  0.1011]])

In [12]:
batch_gray_naive = batch_t.mean(-3)

In [13]:
img_gray_naive, batch_gray_naive

(tensor([[ 0.1262, -0.5537,  0.3009, -0.5066,  0.0779],
         [ 0.6787,  1.2719, -0.4531, -0.5761,  0.9774],
         [-0.4573, -0.4153,  0.1823, -0.1082,  0.2310],
         [ 0.5480,  0.2518, -0.3859, -0.1559, -0.6473],
         [-0.1264, -0.4412,  0.1307,  1.1882, -0.4254]]),
 tensor([[[ 0.5380,  0.2097,  1.0653, -0.3877, -0.4578],
          [-0.2964, -0.6925,  0.2173,  0.2492, -0.1550],
          [ 0.4022, -0.2140,  0.6441, -0.6595, -0.3880],
          [-1.2570,  1.3953,  0.1002,  0.6830,  0.2932],
          [-0.6026,  0.0408,  0.3395, -0.1501,  0.8184]],
 
         [[ 0.2670,  0.6445, -0.2133, -0.1892, -0.3893],
          [-0.1296,  0.3492,  0.2382,  0.2840, -0.3151],
          [-0.6076, -0.1729,  0.5119,  0.5388,  0.1294],
          [-0.6205, -0.0883,  0.9391,  1.0413,  0.4170],
          [ 0.1978, -0.2056, -0.4772, -0.1999,  0.1897]]]))

In [14]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

#### torch.unsqueeze() 在一个维度上扩展

In [15]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [16]:
weights.unsqueeze(-1).unsqueeze_(-1).shape

torch.Size([3, 1, 1])

In [17]:
img_weights = img_t * unsqueezed_weights  # 为什么要加括号?

In [18]:
img_weights

tensor([[[-5.1217e-02, -1.3715e-01,  3.4538e-01, -2.8513e-01,  2.3453e-01],
         [ 4.4647e-01,  2.6088e-01,  5.9544e-02, -2.2623e-01,  4.6451e-01],
         [-1.7499e-01,  7.2632e-02, -6.0416e-02, -1.4403e-02,  1.0911e-01],
         [ 2.4387e-01, -2.3581e-01, -2.0013e-01,  6.1266e-02, -2.1383e-02],
         [ 2.3058e-01, -1.0504e-01, -3.7117e-01,  4.7688e-01, -3.4931e-02]],

        [[ 4.1486e-01, -7.3394e-01, -2.3252e-01, -3.8957e-01, -3.5743e-01],
         [ 8.5333e-01,  8.6335e-01, -9.1600e-01,  4.7461e-01,  1.0723e-01],
         [-2.7749e-01, -1.2851e+00, -7.2919e-03,  2.7932e-01, -6.7390e-02],
         [-1.4703e-02,  8.6330e-01,  4.6714e-02, -4.6351e-01, -8.1971e-01],
         [-1.0631e+00,  5.8194e-01,  1.1501e+00,  1.0795e+00, -1.2952e+00]],

        [[ 2.8409e-03,  7.2880e-04, -2.8640e-02,  2.6422e-02, -2.6681e-02],
         [-9.0768e-02,  9.9740e-02, -2.5896e-02, -9.5861e-02,  4.3131e-02],
         [-1.1619e-02,  1.5104e-02,  6.0730e-02, -4.6743e-02,  1.9787e-02],
        

In [19]:
batch_weights = (batch_t * unsqueezed_weights)

In [20]:
batch_weights

tensor([[[[ 0.3962, -0.1944, -0.0656,  0.2394, -0.0925],
          [ 0.1599, -0.0182,  0.1835, -0.1872,  0.1478],
          [ 0.1975,  0.2234,  0.1717, -0.2465,  0.0762],
          [-0.2872,  0.2119,  0.1809, -0.0350, -0.0304],
          [-0.1412, -0.1709,  0.0884,  0.1302,  0.3949]],

         [[-0.3259,  1.3548,  1.3608,  0.2926,  0.6035],
          [ 0.2432, -1.3031,  0.1087,  1.3330,  0.6271],
          [-0.1311,  0.4769, -0.5489, -0.3911, -0.4883],
          [-1.1532,  0.8202, -0.1008,  0.1691,  0.0900],
          [-0.2137,  0.4733,  0.3072, -0.3367, -0.3279]],

         [[ 0.0149, -0.0253,  0.1156, -0.1948, -0.1287],
          [-0.1430, -0.0123, -0.0262, -0.0170, -0.1471],
          [ 0.0333, -0.1704,  0.1366, -0.0197, -0.0606],
          [-0.0583,  0.1475, -0.0295,  0.1428,  0.0647],
          [-0.0610,  0.0191,  0.0125, -0.0427,  0.0763]]],


        [[[ 0.1715, -0.0047,  0.0600,  0.3093, -0.1840],
          [ 0.1623, -0.0086,  0.0165, -0.0857, -0.1785],
          [-0.1678, -0.

In [21]:
img_gray_weighted = img_weights.sum(-3)

In [22]:
img_gray_weighted

tensor([[ 0.3665, -0.8704,  0.0842, -0.6483, -0.1496],
        [ 1.2090,  1.2240, -0.8824,  0.1525,  0.6149],
        [-0.4641, -1.1973, -0.0070,  0.2182,  0.0615],
        [ 0.2665,  0.6750, -0.1737, -0.4100, -0.8913],
        [-0.8308,  0.3583,  0.8172,  1.5428, -1.2797]])

In [23]:
batch_gray_weighted = batch_weights.sum(-3)

In [24]:
batch_gray_weighted

tensor([[[ 0.0851,  1.1351,  1.4109,  0.3371,  0.3823],
         [ 0.2600, -1.3336,  0.2660,  1.1288,  0.6278],
         [ 0.0996,  0.5299, -0.2406, -0.6573, -0.4728],
         [-1.4987,  1.1795,  0.0505,  0.2768,  0.1243],
         [-0.4159,  0.3215,  0.4081, -0.2492,  0.1433]],

        [[-0.4031,  0.5549, -0.4309,  0.2559, -0.0360],
         [-0.3611, -0.5282,  0.1360,  0.7499,  0.0404],
         [-0.7197,  0.1949,  0.5198,  0.8538, -0.5389],
         [-1.1821, -0.6014,  1.4317, -0.0494,  1.5319],
         [ 0.2061,  0.5915, -0.7140,  0.0961,  0.3962]]])

In [25]:
img_gray_weighted.shape, batch_gray_weighted.shape, unsqueezed_weights.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]), torch.Size([3, 1, 1]))

#### 爱因斯坦乘积

In [26]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)

In [27]:
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)

In [28]:
batch_gray_weighted_fancy.shape, img_gray_weighted_fancy.shape

(torch.Size([2, 5, 5]), torch.Size([5, 5]))

In [30]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0772], names=['channels'])  # 命名是实验特性

C:\Users\WIN10\AppData\Local\Temp\ipykernel_2936\4237662077.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0772], names=['channels'])


# 3.5 张量的元素类型

In [32]:
double_points = torch.ones(10, 2, dtype=torch.double)

double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [37]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [38]:
short_points.dtype

torch.int16

In [46]:
double_points = torch.zeros(10, 2).double()

short_points = torch.ones(10, 2).double()

double_points = torch.zeros(10, 2).to(torch.double)

short_points = torch.ones(10, 2).to(torch.double)

points_64 = torch.randn(5, dtype=torch.double)

points_short = points_64.to(torch.short)

points_64 * points_short  # dtype不同的两个张量操作，会向大的类型转换

tensor([1.4824, -0.0000, -0.0000, 0.0000, 0.0000], dtype=torch.float64)

# 3.6 张量的API

In [49]:
a = torch.ones(3, 2)

a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [51]:
a_t_other = a.transpose(0, 1)

a_t_other.shape

torch.Size([2, 3])

# 3.7 张量的存储视图

In [2]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [3]:
points_storage = points.storage()

In [4]:
points_storage[0]

4.0

In [5]:
points.storage()[1]

1.0

In [8]:
points_storage[0] = 2.0
points_storage, points

( 2.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 tensor([[2., 1.],
         [5., 3.],
         [2., 1.]]))

In [11]:
a = torch.ones(3, 2)
a.zero_()  # 带下划线会改变原有张量，不带下划线会返回一个新张量

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

# 3.8 张量元数据：大小、偏移和步长

In [3]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]
second_points.storage_offset()   # 返回tensor的第一个元素与storage的第一个元素的偏移量

2

In [4]:
second_points.size()

torch.Size([2])

In [5]:
second_points.shape

torch.Size([2])

In [6]:
points.stride()

(2, 1)

In [7]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [8]:
second_point.storage_offset()

2

In [9]:
second_point.stride()

(1,)

In [10]:
second_points.stride()

(1,)

In [11]:
point_t = torch.randn(3,3)
point_t

tensor([[-0.5581,  0.9940,  0.7504],
        [-0.9257, -0.6961,  0.1031],
        [ 0.0229, -2.0957,  2.6469]])

In [12]:
second_point_t = point_t[1]
second_point_t.stride(), point_t.stride(), second_point_t.storage_offset()

((1,), (3, 1), 3)

In [13]:
second_point_t.size(), point_t.size()

(torch.Size([3]), torch.Size([3, 3]))

In [14]:
second_point[0] = 5.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()  # 二维转置
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [17]:
id(points.storage()) == id(points_t.storage())

True

In [18]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [19]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [20]:
some_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))

In [21]:
points.is_contiguous()

True

In [22]:
points_t.is_contiguous()

False

In [23]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [24]:
points_t_cont = points_t.contiguous()

In [25]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [26]:
points_t.stride(), points_t_cont.stride()

((1, 2), (3, 1))

# 3.9 将张量存储到GPU

In [27]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [28]:
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [29]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')
points, points_gpu

(tensor([[ 8.,  2.],
         [10.,  6.],
         [ 4.,  2.]]),
 tensor([[16.,  4.],
         [20., 12.],
         [ 8.,  4.]], device='cuda:0'))

In [30]:
points_gpu = points_gpu + 4
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]], device='cuda:0')

In [31]:
points_gpu = points_gpu.to(device='cpu')
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [32]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

# 3.10 Numpy 互操作性

In [33]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [34]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
points.device

device(type='cpu')

# 3.12 广义张量

In [36]:
torch.save(points, 'F:\jupyter home\data\chapter 3\ourpoints.t')

In [37]:
with open('F:\jupyter home\data\chapter 3\ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [38]:
points = torch.load('F:\jupyter home\data\chapter 3\ourpoints.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
with open('F:\jupyter home\data\chapter 3\ourpoints.t', 'rb') as f:
    points = torch.load(f)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
import h5py

f = h5py.File('F:\jupyter home\data\chapter 3\ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [42]:
f = h5py.File('F:\jupyter home\data\chapter 3\ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [45]:
dset, last_points

(<HDF5 dataset "coords": shape (3, 4), type "<f4">,
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [47]:
last_points = torch.from_numpy(dset[-2:])
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
f.close

<bound method File.close of <HDF5 file "ourpoints.hdf5" (mode r)>>